version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      # This syncs your local files to the container so you don't 
      # have to rebuild Docker every time you change a Pug file.
      - .:/usr/src/app
      - /usr/src/app/node_modules